name = "rdmusic-blog"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-05-05"

[vars]
BUN_VERSION = "1.1.27"
SKIP_DEPENDENCY_INSTALL = "true"